# ============================================================
# 支付宝支付（沙箱）配置
# ============================================================

# 沙箱 APPID
alipay.app-id=9021000158654161

# 商户应用私钥（PKCS8，RSA2）
alipay.merchant-private-key=MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDU8MA+33tK4M6d2o0157XPDSsPtbEvsAJFNnaivNmyNgyfTANIWTQe2ljBuSWvselJ219fHVeuoZSV9u0v0U46kpBfGh0wFHyCxYL2TWfWisCIwkSs8yMmVFGHR17G1dc/HiNkce6AM1RJdnGd5QVeMXRNy/dpjHaV51Ov4dDHSVZ27u7HpcNuEQPmwuoVVXKhZ+a2sTe7sBt1uiSlyGzhOiKmiXnXNg8yQH1Ip2g+ywpEgpD5zFJb6tCVR6ZmmBjR+GRw/yLaBa1VkBDyOkRle6PzPDxSgA2Ds6jokeKTP/Jjl62GCgCLMnnYZLSr17fqZr0y4QJ2NrTQ4J4vdusNAgMBAAECggEBAKMIhRheQOaOgoMnbtBjzLZvLZYElVmel85oKaLlloO0kCtyplzBN3+byzLfT7RaMfRDSpznOVfSDJJZETZ4OT3tMy4tL0W9masCEAgGMcd4Snsqyivkp/fTvOwnP7Baz0dbCtv/wwxSwGjSj6DFVTvN/28FCDO+wJh7GX7jFNdOsHxT/n6qtflixkpCBjebHjUAUNLA3m2WmMV5LuD4mS523OyjxJGCyVqVfDL6sKLM9pOmxoh4W+1glJYQcEC32e7XaQi4cerXWge4AJpuCLXfBvKbcQYH4J9zFYvVdQoAT166QxnTNdxqoGs0s/liH3WmwqgPONFqPPCNCdbcAp0CgYEA8MrVI2xgn/BVCr0N15/rT7OMAaWrQxppLihR9iwP1wpne1Zdx0JB9MOWksJYl6x6Q5sZb/t6sU3GkYLUPc+9C4utMhl7s64Rq0//mHq1IfUQRhH+syI3WNFja/PZ169FgvIwPeUci8RIhmxAtIF7/UeT+nYO0nTW5nKCTdIVa18CgYEA4mOa1/2bjVCo8IpcqH5GY1sWvIF3aqvVNT/jFeDUK7QEZ9uXy+GFiOMq1o7yLkgNwpemJaph3yWt6YT771C9O5i+kpGgjYl3GQf3mXq0nMoKmWK4ctb3AVImAmbB572ua210/3T6VcZA09jtvEnwVtFXdec+ibwqiPPlapgn7RMCgYAjC0INz74YSN/3miAjm5Chnt3nd3b/Yx6fqxqSm0MK5ua8mos3brsupjCJ12MRX/bDVBVVqOHoYAtgLgw5mrxGq+NfATpxognMRu5KAMHP2Vyu9ft9kqM/d+niUjEIJOgW8Kx4tZl79esgNS0NmDK1X+93aisqEfscutmf/c1EPQKBgQDedF2dS9jj/ZRj+LGf56Um0EUBKn67VOoGjyaHQwt5fkSuATuh3ZMntYFMn94d2DOdOQLMFCZj7VR9GG2u9TldLHRm9a48Jg3fjNKh/88mGepcWoNAZTcGF0C+L1bubpbLfRzwQHQUgOEGyiyhTk5aIQ6+DmKHWVy6gl62ZZkl/QKBgAbrl18G1pmm65pOc/YFFYPNMzXNeqALQcMXmlYSQE/+0s2W9QlnJIxGr+i9N2GxusUNFr5/hZmAwE40aFsJDtWZFt49CQ7Wf9UsR72PVyczMIORZJM+CekJPe6zxVSrGkRukAGgaWA3SBCQtR+80mbIfuvygWJt9d/x8IHuVpzH

# 支付宝公钥（沙箱应用的支付宝公钥）
alipay.alipay-public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmKF87dNs/6AlnfFGzFP9MOe+IXA9B7l/TJS1NlV2tjr0EIoeCMOXyyDXIt6jlLm+u1eDImOopifJv7/R7MN56PTIrJu4iDwMBrimBhb1bye6TnV0aQruqbt3MPggjH1DpcnoNuAFVquysOUKwGv0CGbFw0NfVR3uM1nnF/CXCtEL7ySS35jZgsVmuQK4yEGyPjx1om4fqsEZFYnrj+5TMwxETjJv7/1/JZmueoGObeEd7MJVOon9DFDW/T6rWYgpeCnDM81irHADypXpWf8kyWiwIqlBVsUiFk6W22PLJI1b69qHqqmh5aHm7QN1NQAQJjRtQLMhJnKUWPoGHH96jQIDAQAB

# 签名类型
alipay.sign-type=RSA2

# 字符集
alipay.charset=UTF-8

# 格式
alipay.format=json

# 网关（沙箱：openapi-sandbox.dl.alipaydev.com，正式：openapi.alipay.com）
alipay.gateway-url=https://openapi-sandbox.dl.alipaydev.com/gateway.do

# 通知域名（公网可访问到你后端的域名，例如 ngrok）
# 最终回调地址 = {alipay.notify-domain}/api/pay/alipay/notify
alipay.notify-domain=https://unnihilistic-diagonally-mack.ngrok-free.dev
